AUTO_SHIFT_ENABLE    = yes
TAP_DANCE_ENABLE     = yes
GERMAN_ENABLE        = yes # enable us layout on german keyboards
CONSOLE_ENABLE       = no
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE      = yes
REPEAT_KEY_ENABLE    = yes
# KEY_LOCK_ENABLE      = yes
# DEFERRED_EXEC_ENABLE = yes
