#pragma once

#define IGNORE_MOD_TAP_INTERRUPT

#undef TAPPING_TERM
#define TAPPING_TERM 200

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1500

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 200
#define LEADER_PER_KEY_TIMEOUT
